### PR TITLE
Push to github registry as well

### LINKED ISSUE #235: [Enhancement] Publish Docker images to GHCR
With Docker Hub's addition of pull limits this past November, it would be nice if Docker images were mirrored on GitHub Container Registry, which doesn't have any limits (for now at least).

https://github.blog/2020-09-01-introducing-github-container-registry/

(Note that this is different from "GitHub Packages.")

### PR DESCRIPTION
**Pull request by mbround18**
# Description

## Contributions
- Added githubs registry
- closes #235

## Checklist

- [x] I added one or multiple labels which best describes this PR.

### CODE REVIEW

**Comment by TheCatLady** [comment]
@mbround18 You need to log in to GHCR and update the image tag to not include `registry.hub.docker.com/` 😉  I personally really like docker/login-action, crazy-max/ghaction-docker-meta, and docker/build-push-action for this purpose.

**Comment by TheCatLady** [comment]
@mbround18 Additional info on GHCR here, if you need it: https://docs.github.com/en/packages/guides/migrating-to-github-container-registry-for-docker-images

**Comment by mbround18** [comment]
Nah i saw my goof :P 

the flow already logs into ghcr in an earlier step, I just forgot to remove the registry for docker

**Comment by TheCatLady** [comment]
> Nah i saw my goof :P
> 
> the flow already logs into ghcr in an earlier step, I just forgot to remove the registry for docker and tag it with the registry I wanted to publish to
Just FYI, this won't log you in to GHCR:
```
          echo "${{ github.token }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin
```
A PAT is required to log in to GHCR.

**Comment by TheCatLady** [comment]
@mbround18 Closer, but still not 100% correct in 657c98e1ec37aa2494226904505313e7a7330194. 😅  Should be the following:
```
          echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
```

**Comment by mbround18** [comment]
> @mbround18 Closer, but still not 100% correct in [657c98e](https://github.com/mbround18/valheim-docker/commit/657c98e1ec37aa2494226904505313e7a7330194). 😅 Should be the following (`ghcr.io` instead of `docker.pkg.github.com`):
> 
> ```
>           echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
> ```

Lol ill update it in a moment, I'm doing a bit of context switching nd apologies for the scatterbrain :P

**Comment by TheCatLady** [comment]
@mbround18 No worries, I really appreciate your promptness in addressing my request!  I didn't expect it to happen literally minutes after I submitted the GitHub issue 😄  I would have just submitted a PR if it weren't necessary for the GHCR token to be added as a repo secret.

**Comment by mbround18** [comment]
It should be up shortly, I had an extra double quote way down 🙄

**Comment by mbround18** [comment]
Should be live now, I saw the release notification go out. I dont see the packages section here on github tho.

**Comment by TheCatLady** [comment]
> Should be live now, I saw the release notification go out. I dont see the packages section here on github tho.

New GHCR images default to private, so you need to modify the visibility setting here: https://github.com/mbround18?tab=packages

**Comment by mbround18** [comment]
https://github.com/users/mbround18/packages/container/package/valheim

and

https://github.com/users/mbround18/packages/container/package/valheim-odin

**Comment by TheCatLady** [comment]
@mbround18 Yay, thanks so much!  And not a big deal, but from those pages you can also link the repo so that the README appears and the package will be listed on the repo page. :)

**Pull request merged**
