### PR TITLE
Update Dockerfile

### PR DESCRIPTION
**Pull request by dyyce**
# Description
adding syntax as comment

## Contributions
- I added the line at the top, otherwise container services (aws, do, render) will throw an error `Dockerfile parse error line 47: Unknown flag: chmod`

## Checklist

- [ ] I added one or multiple labels which best describes this PR.
- [ ] I have tested the changes locally.
- [ ] This PR has a reviewer on it. 
- [ ] I have validated my changes in a docker container and on Ubuntu. (Only needed for Odin or Docker Changes)

### CODE REVIEW

**Comment by mbround18** [comment]
What docker compose version are you using? This is valid docker and shouldn't need to include the experimental flags.

**Comment by mbround18** [comment]
My bad I read your comment in the PR wrong, does aws not allow chmod?

**Comment by dyyce** [comment]
hey,

I am using `docker-compose version 1.27.3, build 4092ae5d`. I get the error when I try to run using `docker-compose up` and also when I try to run just the Dockerfile (which does not make sense, but I wanted to give it a shot).

**Comment by dyyce** [comment]
another way of fixing it is to run these two lines from this post https://github.com/docker/compose/issues/7252#issuecomment-616767577

* `export COMPOSE_DOCKER_CLI_BUILD=1`
* `export DOCKER_BUILDKIT=1`

**Comment by mbround18** [comment]
What is your docker version? Mine are currently: 
```
docker-compose version 1.27.4, build 40524192
Docker version 20.10.2, build 2291f61
```

**Comment by azgaviperr** [comment]
One other solution is to remove the --chmod and --chown and RUN chmod and RUN chown instead

**Comment by mbround18** [comment]
> One other solution is to remove the --chmod and --chown and RUN chmod and RUN chown instead

Maybe you can provide more context to where this issue is coming up? The supported docker and docker-compose versions are: 

```
docker-compose version 1.27.4, build 40524192
Docker version 20.10.2, build 2291f61
```

It is a better practice to use --chown and --chmod within the copy command vs creating a separate run command for them or stacking them in an existing command.

**Comment by Richi2293** [comment]
I ran into this problem too, one solution is to simply split the command because the CHMOD inside the COPY command was not taken. (I had this problem using DOKKU, otherwise with a normal docker-compose the problem did not occur)

Example currently command:
`COPY --chmod=755 ./src/scripts/*.sh /home/steam/scripts/`

You can write it like this:
`COPY ./src/scripts/*.sh /home/steam/scripts/`
`CHMOD 755 -R /home/steam/scripts/`

**Comment by mbround18** [comment]
So something like this? 
image

**Comment by mbround18** [comment]
See #148 which should include updated dockerfile configs. Could one of yall review it?

**Pull request closed without merging**
