### PR TITLE
Avoid compiling odin twice in dockerfile

### PR DESCRIPTION
**Pull request by LovecraftianHorror**
# Description

## Contributions

Unless I'm missing something there is no need to do `cargo install` and `cargo build --release` in `Dockerfile.odin`. `cargo install` will build the executable in a temporary directory and install it into `$HOME/.cargo/bin` while `cargo build --release` will compile the executable in `{PROJECT_DIR/target/release` which I believe is the only one needed in this case.

It's possible that `mbround18/valheim-odin` has some other usage that I'm missing since I'm not super familiar with `docker`, but if not then this should also cut down on image build times. Even if the executable is needed in both places then you could simply use `cargo install` and then copy the executable to `/data/odin/target/release/odin` instead of building it twice.

I finally got everything setup where I can easily test local builds of both images correctly, so I was able to test this one locally and noticed no odd behavior from running the `valheim` container.

## Checklist

- [ ] I added one or multiple labels which best describes this PR.
- [ ] I have tested the changes locally.
- [ ] This PR has a reviewer on it. 
- [ ] I have validated my changes in a docker container and on Ubuntu. (Only needed for Odin or Docker Changes)

### CODE REVIEW

**Comment by mbround18** [comment]
Odin compiled into its own docker image is for separation of concerns. Tbh I didn't know build will also install :P 

As for odin in its own docker, I use it for cron jobs on kubernetes to perform the same jobs that the auto update script does. Imo having multiple processes run inside a container is something I like to avoid.

**Comment by LovecraftianHorror** [comment]
That all makes a lot of sense. I'm very new to docker since I've only really been using it a bit to host some game servers. So if all that matter is the odin executable pointed to by `ENTRYPOINT` then I think this should be all good.

And I also find it a bit confusing, but its due to people wanting cargo to be used to build and install rust tools that people made _as well as_ all the project management stuff you would except, so `build` is for the current project while install can be for a local project or from ones that people upload to crates.io

**Comment by LovecraftianHorror** [comment]
Oh and final comment. So the place where odin is built with `cargo build` is likely not in `$PATH` if that matters in which case copying the executable would be an easy fix. I wasn't sure how to use the `odin` container by itself.

Sorry for the spam, just trying to be thorough since I don't have the best grasp of the full situation.

**Comment by mbround18** [comment]
> Oh and final comment. So the place where odin is built with `cargo build` is likely not in `$PATH` if that matters in which case copying the executable would be an easy fix. I wasn't sure how to use the `odin` container by itself.
> 
> Sorry for the spam, just trying to be thorough since I don't have the best grasp of the full situation.

This does not really matter for the odin docker image as you change the CMD being passed to the docker image when using it to execute other odin commands.

**Review by mbround18 — APPROVED** [review]

**Pull request merged**
