### PR TITLE
fixes relative link for mods tutorial

### PR DESCRIPTION
**Pull request by jtbg**
Previously, the "Environment Variables" table contained a [rotted link](https://en.wikipedia.org/wiki/Link_rot) for the "Getting Started with Mods" tutorial.

This replaces the link to properly point to the intended file.

### CODE REVIEW

**Comment by mbround18** [comment]
Oop thank you @jtbg! :)

**Review by mbround18 — APPROVED** [review]

**Comment by jtbg** [comment]
Considering how long it took for someone to mention it, it might not even be needed to link there

**Comment by mbround18** [comment]
I agree, considering CI is giving me some troubles, ill have to take a look at this tomorrow (its pretty late for me now)

**Comment by mbround18** [comment]
For some reason, github doesnt want to run the docker build on this pr. Added a PR incorporating these changes: #482

**Pull request closed without merging**
