### PR TITLE
Update README.md - add ulimits to docker-compose

### PR DESCRIPTION
**Pull request by ianhattendorf**
`steamcmd.sh` attempts to set `ulimits -n 2048`, which generally won't be allowed inside a docker container. Set them at the docker-compose level to allow this command to succeed.

### CODE REVIEW

**Comment by mbround18** [comment]
Is this required? or optional?

**Comment by ianhattendorf** [comment]
It's probably fine to ignore, but I would imagine there's a reason for it. Might only be necessary in specific situations.

https://developer.valvesoftware.com/wiki/SteamCMD#ulimit_Linux_startup_error

**Comment by zackbcom** [comment]
I tried with these settings and it lags the server on my dual xeon. Once removed the lag went away. I would recommend to not add these.

**Comment by mbround18** [comment]
Closing due to testing on multiple processors and multiple systems. It causes host lag and for a multi tenant host it can wreak havoc

**Comment by ianhattendorf** [comment]
Interesting, I didn't notice any issues on my server (an older sandybridge dual xeon, docker inside a proxmox VM with multiple docker containers and multiple other VMs). I wonder if something else is at play, I'll keep on eye on it locally.

**Pull request closed without merging**
