### PR TITLE
Fix #32 &  #30 background the tail command and wait

### LINKED ISSUE #32: Use SIGINT for server shutdown
as of version 0.143.5 the server process no longer uses the file marker to note shutdown. It instead will use honor SIGINT. 

https://steamcommunity.com/games/892970/announcements/detail/3059603085893784927

Since this is no longer used https://github.com/mbround18/valheim-docker/blob/main/src/files/server_exit.rs#L14-L18 should be updated to send a SIGINT to the process rather than writing to the file and waiting for shutdown

### PR DESCRIPTION
**Pull request by spion06**
# Description

resolves issues with shutdown in docker/kube due to SIGTERM being swallowed by bash due to it waiting for a process to complete. https://ss64.com/bash/trap.html gives the clearest explanation of this

> When Bash receives a signal for which a trap has been set while waiting for a command to complete, the trap will not be executed until the command completes. When Bash is waiting for an asynchronous command via the wait built-in, the reception of a signal for which a trap has been set will cause the wait built-in to return immediately with an exit status greater than 128, immediately after which the trap is executed.

## Contributions
- #32 & #30 backgrounded tail to avoid bash from blocking trap execution until it completes (tail will never complete)
- put function before trap definition to avoid any issues/race conditions with the function not being defined when the trap is made

## Checklist

- [x] I added one or multiple labels which best describes this PR.
- [x] I have tested the changes locally.
- [x] This PR has a reviewer on it. 
- [x] I have validated my changes in a docker container and on Ubuntu. (Only needed for Odin or Docker Changes)

### CODE REVIEW

**Comment by spion06** [comment]
@mbround18 this should resolve the issues with traps not executing that we discussed in #32

**Comment by mbround18** [comment]
Hey my bad, I had rearranged some files and their responsibilities since they were getting a bit jumbled. When I add these changes locally to whats on main at the moment I am still getting a exit code of 137.

**Comment by spion06** [comment]
so in the latest version i see in main tail isn't backgrounded. this is required otherwise the trap will never execute

**Comment by spion06** [comment]
updated this PR with the relevant changes

**Comment by mbround18** [comment]
Would you mind removing the while loop? No need in having it if the command above isnt going to finish.

**Comment by spion06** [comment]
removed in latest commit

**Comment by mbround18** [comment]
How did you test this? When I tested locally, I still got a 137 from the container on stop. 
image


Btw, if you rebase your branch from the repos main branch you should be able to not have to build rust each time. 

My tests steps were: 
- `docker-compose build valheim`
- `docker-compose start valheim`
- `docker-compose logs -f valheim`
- In a new terminal, `docker-compose stop valheim` (after the server fully started successfully)

**Comment by spion06** [comment]
```
docker build .
docker run <image id from docker build output>

# separate terminal
docker stop <container id>
```

after running docker stop i see in the log output

```
[Valheim][steam]: Halting server! Received interrupt!
[ODIN][INFO]  - Stopping server /home/steam/valheim
[ODIN][INFO]  - Scanning for Valheim process
[ODIN][INFO]  - Found Process with pid 91! Sending Interrupt!
[ODIN][INFO]  - Process signal interrupt sent successfully!
/home/steam/scripts/start_valheim.sh: line 52: kill: (94) - No such process
[Valheim][steam]: Halting server! Received interrupt!
[ODIN][INFO]  - Stopping server /home/steam/valheim
[ODIN][INFO]  - Scanning for Valheim process
[ODIN][INFO]  - Found Process with pid 91! Sending Interrupt!
[ODIN][INFO]  - Process signal interrupt sent successfully!
```

**Comment by spion06** [comment]
i did a quick test inside the container and didn't see the non-zero exit code

```
$ docker run -it --entrypoint bash dd3803d054f1
root@0f57faa37e85:/home/steam/steamcmd# bash /entrypoint.sh /bin/bash /home/steam/scripts/start_valheim.sh
#.... startup output
Unloading 490 unused Assets to reduce memory usage. Loaded Objects now: 86244.
Total: 81.715100 ms (FindLiveObjects: 3.504100 ms CreateObjectMapping: 10.689600 ms MarkObjects: 62.054000 ms  DeleteObjects: 5.450800 ms)

02/10/2021 17:52:17: Zonesystem Start 205

(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)

02/10/2021 17:52:17: Generating locations

(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)

02/10/2021 17:52:17: Checking for location duplicates

(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
```

exec a shell in the container and give it a SIGTERM
```
yuno-PC:~$ docker exec -it 0f57faa37e85 bash
root@0f57faa37e85:/home/steam/steamcmd# apt-get install procps
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
  libprocps7
The following NEW packages will be installed:
  libprocps7 procps
0 upgraded, 2 newly installed, 0 to remove and 1 not upgraded.
Need to get 321 kB of archives.
After this operation, 871 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://deb.debian.org/debian buster/main amd64 libprocps7 amd64 2:3.3.15-2 [61.7 kB]
Get:2 http://deb.debian.org/debian buster/main amd64 procps amd64 2:3.3.15-2 [259 kB]
Fetched 321 kB in 0s (1605 kB/s)
debconf: delaying package configuration, since apt-utils is not installed
Selecting previously unselected package libprocps7:amd64.
(Reading database ... 11290 files and directories currently installed.)
Preparing to unpack .../libprocps7_2%3a3.3.15-2_amd64.deb ...
Unpacking libprocps7:amd64 (2:3.3.15-2) ...
Selecting previously unselected package procps.
Preparing to unpack .../procps_2%3a3.3.15-2_amd64.deb ...
Unpacking procps (2:3.3.15-2) ...
Setting up libprocps7:amd64 (2:3.3.15-2) ...
Setting up procps (2:3.3.15-2) ...
update-alternatives: using /usr/bin/w.procps to provide /usr/bin/w (w) in auto mode
update-alternatives: warning: skip creation of /usr/share/man/man1/w.1.gz because associated file /usr/share/man/man1/w.procps.1.gz (of link group w) doesn't exist
Processing triggers for libc-bin (2.28-10) ...
root@0f57faa37e85:/home/steam/steamcmd# ps -ef
UID        PID  PPID  C STIME TTY          TIME CMD
root         1     0  0 17:48 pts/0    00:00:00 bash
steam       78     1  0 17:51 pts/0    00:00:00 /bin/bash /home/steam/scripts/start_valheim.sh
root       156     0  0 17:51 pts/1    00:00:00 bash
steam      172     1 99 17:51 pts/0    00:00:11 /home/steam/valheim/valheim_server.x86_64 -port 2456 -name Valheim Docker -world Dedicated -password 12345 -public 1
steam      173     1  0 17:51 pts/0    00:00:00 tee ./output.log
steam      175    78  0 17:51 pts/0    00:00:00 tail -f /home/steam/valheim/output.log
root       262   156  0 17:52 pts/1    00:00:00 ps -ef
root@0f57faa37e85:/home/steam/steamcmd# kill 78
```

logs from the other terminal running the process
```
[Valheim][steam]: Halting server! Received interrupt!
[ODIN][INFO]  - Stopping server /home/steam/valheim
[ODIN][INFO]  - Scanning for Valheim process
[ODIN][INFO]  - Found Process with pid 172! Sending Interrupt!
[ODIN][INFO]  - Process signal interrupt sent successfully!
[Valheim][steam]: Halting server! Received interrupt!
/home/steam/scripts/start_valheim.sh: line 52: kill: (175) - No such process
[ODIN][INFO]  - Stopping server /home/steam/valheim
[ODIN][INFO]  - Scanning for Valheim process
[ODIN][INFO]  - Found Process with pid 172! Sending Interrupt!
[ODIN][INFO]  - Process signal interrupt sent successfully!
root@0f57faa37e85:/home/steam/steamcmd# echo $?
0
```

**Comment by spion06** [comment]
i'm wondering if the issue you are seeing there is from docker-compose not starting a new container and instead re-using an existing one. 

if i use the steps you noted i receive an error
```
yuno-PC:~/valheim-docker$ docker-compose start valheim
Starting valheim ... failed
ERROR: No containers to start
```

however using `docker-compose up valheim`  created the containers for me

**Comment by spion06** [comment]
note that the container ID is the same both pre and post startup after doing the initial container creation. 
```
yuno-PC:~/valheim-docker$ docker ps -a | grep valheim
5c4964cee55c   mbround18/valheim:latest        "/bin/bash /entrypoi…"   4 minutes ago    Exited (0) About a minute ago             valheim-docker_valheim_1
05756355979b   mbround18/valheim-odin:latest   "bash"                   4 minutes ago    Exited (0) 3 minutes ago                  valheim-docker_odin_1
yuno-PC:~/valheim-docker$ docker-compose up valheim
Starting valheim-docker_odin_1 ... done
Starting valheim-docker_valheim_1 ... done
Attaching to valheim-docker_valheim_1
valheim_1  |
valheim_1  | ###########################################################################
valheim_1  | Valheim Server - Wed Feb 10 20:10:16 CST 2021
valheim_1  |
valheim_1  | Initializing your container...
valheim_1  | ###########################################################################
#.... startup output
valheim_1  |     Vendor:   Unity Technologies
valheim_1  | Begin MonoManager ReloadAssembly
valheim_1  | - Completed reload, in  0.089 seconds
valheim_1  | UnloadTime: 0.571100 ms
valheim_1  | 02/10/2021 20:10:20: Starting to load scene:start
valheim_1  |
valheim_1  | (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
valheim_1  |
valheim_1  | Couldn't create a Convex Mesh from source mesh "RearBig" within the maximum polygons limit (256). The partial hull will be used. Consider simplifying your mesh.
valheim_1  | (Filename:  Line: 91)
valheim_1  |
^Z
[2]+  Stopped                 docker-compose up valheim
yuno-PC:~/valheim-docker$ bg
[2]+ docker-compose up valheim &
yuno-PC:~/valheim-docker$ docker ps
CONTAINER ID   IMAGE                      COMMAND                  CREATED         STATUS          PORTS                              NAMES
5c4964cee55c   mbround18/valheim:latest   "/bin/bash /entrypoi…"   4 minutes ago   Up 11 seconds   0.0.0.0:2456-2458->2456-2458/udp   valheim-docker_valheim_1
```

if i give my docker-compose command the `--force-recreate` it actually uses the new image that was built

```
yuno-PC:~/valheim-docker$ docker-compose up --force-recreate valheim
Recreating valheim-docker_odin_1 ... done
Recreating valheim-docker_valheim_1 ... done
Attaching to valheim-docker_valheim_1
#... startup output + ctrl-z/bg
yuno-PC:~/valheim-docker$ docker ps
CONTAINER ID   IMAGE                      COMMAND                  CREATED          STATUS          PORTS                              NAMES
9dc5c5351379   mbround18/valheim:latest   "/bin/bash /entrypoi…"   48 seconds ago   Up 47 seconds   0.0.0.0:2456-2458->2456-2458/udp   valheim-docker_valheim_1
```

**Comment by mbround18** [comment]
I see what happened, after digging around its the tail command that was the cause of the grief. Thank you for looking into this!

**Review by mbround18 — APPROVED** [review]

**Pull request merged**
