### PR TITLE
Added BepInEx Support

### LINKED ISSUE #130: [Feature] Add mod support through BepInEx
Valheim has a bunch of mods available on NexusMods that work when loaded through the [BepInEx modding framework](https://github.com/BepInEx/BepInEx) / https://www.nexusmods.com/valheim/mods/4 . Downloading them and shoving them on the volumes on this docker doesn't work because it needs extra setup on unix. https://bepinex.github.io/bepinex_docs/master/articles/user_guide/installation/index.html?tabs=tabid-nix

### PR DESCRIPTION
**Pull request by mbround18**
# Description

## Contributions
- Added BepInEx Support
- Cleaned up some linting 
- Closes #130
- Closes https://github.com/mbround18/valheim-docker/issues/150
- Closes https://github.com/mbround18/valheim-docker/pull/72
- Included zip and unzip in Dockerfile for downloading & installing mods
- 

## Checklist

- [x] I added one or multiple labels which best describes this PR.
- [x] I have tested the changes locally.
- [x] This PR has a reviewer on it. 
- [x] I have validated my changes in a docker container and on Ubuntu. (Only needed for Odin or Docker Changes)

### CODE REVIEW

**Comment by mbround18** [comment]
As @AtroposOrbis pointed out, there is a new multiplayer addition called longship. Ill make a change where the dll loaded can be longship :)

**Comment by mbround18** [comment]
See https://github.com/mbround18/valheim-docker/discussions/149 for testing related to this pull request...

**Comment by AtroposOrbis** [comment]
Been running for two days now. Longship only. No errors and amazing performance <3

**Comment by mbround18** [comment]
This is getting merged in, tonight at 5pm PST

**Comment by paulmoore** [comment]
@mbround18 Apologies if the answer to this is obvious but I was still a little confused even after reading the updated documentation in this PR. Is it expected that to enable BepInEx we manually install it from the container after launching it?

**Comment by mbround18** [comment]
> @mbround18 Apologies if the answer to this is obvious but I was still a little confused even after reading the updated documentation in this PR. Is it expected that to enable BepInEx we manually install it from the container after launching it?

@paulmoore yes, there are so many versions of BepInEx, Doorstop, and other mods floating around that it would be impossible for me to track down a reliable version for installation. Since modding is in its infancy for Valheim right now, you will have to manually install `BepInEx`, `Doorstop`, and the reconstructed libraries that Valheim uses. Ill have a guide up in a little bit about how to install `BepInEx` inside the container using `ValheimPlus` as an example mod.

**Pull request merged**
