### PR TITLE
Multiple small fixes

### LINKED ISSUE #37: Configuring the auto update time
The docs say:
```
Set to 1 if you want your container to auto update! This means at 1 am it will update, stop, and then restart your server.
```

Is there a way to configure that so it restarts at 9am for example?

### PR DESCRIPTION
**Pull request by Shuro**
# Multiple small fixes

## Contributions
- Add libsdn2.0-0.0 to fix `Warning: failed to init SDL thread priority manager: SDL not found` error
- Apply docker best practice (clear apt cache)
- Kill tee after odin stop server
- Remove deprecated script call in update routine
- Modified auto-update routine to make variable update times possible (fix #37) 

## Checklist

- [ ] I added one or multiple labels which best describes this PR.
- [x] I have tested the changes locally.
- [ ] This PR has a reviewer on it. 
- [x] I have validated my changes in a docker container and on Ubuntu. (Only needed for Odin or Docker Changes)

## Log Output
```
[...]
02/11/2021 03:33:02: DungeonDB Start 181

(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)


^C[Valheim][steam]: Halting server! Received interrupt!
[ODIN][INFO]  - Stopping server /home/steam/valheim
[ODIN][INFO]  - Scanning for Valheim process
[ODIN][INFO]  - Found Process with pid 91! Sending Interrupt!
[ODIN][INFO]  - Process signal interrupt sent successfully!
[ODIN][INFO]  - Waiting for server to completely shutdown...
02/11/2021 03:34:03: Game - OnApplicationQuit

(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)

02/11/2021 03:34:03: ZNet Shutdown

(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)

02/11/2021 03:34:03: clone 1

(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)

02/11/2021 03:34:03: Saved 81 zdos

(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)

02/11/2021 03:34:03: World saved ( 7.54ms )

(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)

02/11/2021 03:34:03: Sending disconnect msg

(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)

02/11/2021 03:34:03: Disposing socket

(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)

02/11/2021 03:34:03: Closing socket 0

(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)

02/11/2021 03:34:03: Last socket, unregistering callback

(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)

02/11/2021 03:34:03: ZSteamSocket  UnregisterGlobalCallbacks, existing sockets:0

(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)

Setting up 6 worker threads for Enlighten.
  Thread -> id: 7f655b284700 -> priority: 1
  Thread -> id: 7f655aa83700 -> priority: 1
  Thread -> id: 7f655a282700 -> priority: 1
  Thread -> id: 7f6559a81700 -> priority: 1
  Thread -> id: 7f6559280700 -> priority: 1
  Thread -> id: 7f6558a7f700 -> priority: 1
02/11/2021 03:34:03: Steam manager on destroy

(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)

[ODIN][INFO]  - Server has been shutdown successfully!
```

### CODE REVIEW

**Comment by Shuro** [comment]
Honestly not even sure if killing `tee` is really necessary. ^^

**Comment by mbround18** [comment]
Hey @Shuro excellent additions! Would you mind taking the implementation a step further with the cron updates? I was thinking moving the cron setup into the `entrypoint.sh` and dynamically build the auto_update cron job using `echo` or `printf`. That way we could change the cron `START_HOUR` variable to be `CRON_SCHEDULE` and virtually take any time set. 

Basically we want a variable that supplies the time format of a standard cron job and then we could remove the check in the script for the hour. 
https://crontab.guru/

Additionally then we can remove the update check inside of the actual auto_update script and move it to the `entrypoint.sh` where it only creates the cronjob If they have `AUTO_UPDATE` in the environment as a variable.

**Comment by mbround18** [comment]
@Shuro Excellent work <3 I have incorporated your changes along with mine in #53

**Comment by Shuro** [comment]
Sure @mbround18, I'll take a look tomorrow / today. :) I'll create a merge request then.

**Comment by Shuro** [comment]
@mbround18 Mhm I don't find 
- Add libsdn2.0-0.0 to fix Warning: failed to init SDL thread priority manager: SDL not found error
-Apply docker best practice (clear apt cache)
incorporated in your changes in #53

**Pull request closed without merging**
