### PR TITLE
Player join/leave webhook

### PR DESCRIPTION
**Pull request by mbround18**
# Description

## Contributions

- [x] Added webhook to discord file
- [x] Added line in log parse looking for join/leave

## Checklist

- [x] I added one or multiple labels which best describes this PR.
- [x] I have tested the changes locally.
- [ ] This PR has a reviewer on it.
- [ ] I have validated my changes in a docker container and on Ubuntu. (Only needed for Odin or Docker Changes)

### CODE REVIEW

**Comment by mbround18** [comment]
I am still thinking though how to best implement this, in the logs they dont really have great messages that are succinct. im thinking of creating a players.list in the game folder that tracks visitors

**Comment by mbround18** [comment]
@andrewgdunn im sorry this took so long, getting back into it now.

Got some good progress! 

image

**Comment by andrewgdunn** [comment]
I love it! Thanks for being willing to prototype this!

**Comment by mbround18** [comment]
@andrewgdunn if u wanna give it a play test the docker image is 

```
mbround18/odin:sha-d23b102
```

and the flag to enable it is 

```
PLAYER_EVENT_NOTIFICATIONS=1
```

**Comment by andrewgdunn** [comment]
Am I confused, this is like a ~100MB image: `mbround18/odin:sha-d23b102`

**Comment by andrewgdunn** [comment]
Works great!

**Comment by mbround18** [comment]
Thank you @andrewgdunn  burn in test is complete, this has been merged :) this is available on 

https://github.com/mbround18/valheim-docker/releases/tag/v3.0.6

**Pull request merged**
