### PR TITLE
Daemonized start

### PR DESCRIPTION
**Pull request by mbround18**
# Description

## Contributions
- Use rust specific start
- Added Config for launching start
- Added husky to commits which require you to build and test in linux or a wsl on windws. 

## Checklist

- [x] I added one or multiple labels which best describes this PR.
- [x] I have tested the changes locally.
- [x] This PR has a reviewer on it. 
- [x] I have validated my changes in a docker container and on Ubuntu. (Only needed for Odin or Docker Changes)

## Tests

- Tested with funky characters in password
- Any character that docker-compose allows you to add to the `environment` it lets you use
- It now properly backgrounds the process without dropping to shell
- No more down to shell 🚀 
- Added `nographics` flag to make the server not load the gui portion. (WHY valheim devs WHY you add weird stuff like this??)

### CODE REVIEW

**Comment by mbround18** [comment]
@LovecraftianHorror I would appreciate your eyeballs on this one when you get a chance :)

**Comment by LovecraftianHorror** [comment]
I really like the changes I saw. There was nothing major sticking out to me although I can start a review for really minor stuff, but I was planning on going through with a PR just to clean up all the Rust code a bit. The one thing I was hesitant about is exposing an env var for `ODIN_CONFIG_PATH`. I see that it's only used in unit testing (which is great that there's starting to be unit testing! Was gonna add that in more before I start making more changes). Ideally the config location would be something like `$XDG_CONFIG_HOME/odin/config.json` with something like the [dirs crate](https://lib.rs/crates/dirs) to make it easier. Setting a custom location for testing can be done by a structure like

```rust
fn default_config_location() -> ManagedFile {
    // Similar to what was in `config_file` before
    ...
}

fn read_config(config: ManagedFile) -> ValheimArguments {
    ....
}
```

And then that makes it so that for normal use you can just do `read_config(default_config_location))` and then in testing you can pass in a custom location. Also for testing I would recommend creating a `tempdir()` from the [tempfile crate](https://lib.rs/crates/tempfile) and placing the dummy config there seems nicer than creating a randomly named file in the current directory.

I like seeing the addition of `cargo-husky` too. I've seen people mention it before, but never used it personally. It seems very useful.

I'm definitely very happy with the direction of this change though. Getting to avoid the complexity of creating the start script is much nicer!

**Comment by mbround18** [comment]
Hey @LovecraftianHorror hope you are feeling better!

In the case of exposing the env variable, it's a better practice to enable versatility. In this docker containers case, since the odin docker image is used on kubernetes the config file will actually be written as a config map for utilization in cron jobs as well as the deployment. That is my current use case as I am now running 10-15 servers in my cluster. Although, I believe I should update it to follow standard naming conventions for secret vars like this and have it end with `_FILE ` which is more common when mounting. 


As for cleaning up the rust code, I included husky (which I use in js based projects a lot) for cleaning up what's going on. Is there any other tools I should be using to clean up deps or such?

**Comment by LovecraftianHorror** [comment]
I am all better now, thanks for the concern!

That sounds like a fair use case then. I can see how it would be better to expose it with an env var when using docker.

And the cleanup would really just be a once-over to try and make everything more idiomatic if possible. Nothing in particular, but something that requires a human touch.

**Pull request merged**
