### PR TITLE
16 ability to change steam userid

### PR DESCRIPTION
**Pull request by mbround18**
# Description

## Contributions
- Changed to starting the container as root
- Added init script as root.
- Added log blocks for clarity.
- Added more context to entry point. 

## Checklist

- [x] I added one or multiple labels which best describes this PR.
- [x] I have tested the changes locally.
- [x] This PR has a reviewer on it. 
- [x] I have validated my changes in a docker container and on Ubuntu. (Only needed for Odin or Docker Changes)

### CODE REVIEW

**Comment by mbround18** [comment]
I would really appreciate if someone who is using a separate user ID could assist in testing this functionality.

**Comment by Fabiryn** [comment]
tested it locally. The generated files now have the right user id.
server starts normally `valheim_1  | 02/08/2021 23:51:45: Game server connected`

Not sure if this is an issue with the changes but, TZ doesn't get respected. I'll test it later with the official release.

**Comment by Fabiryn** [comment]
So the TZ environment only seems to work for the init.sh logs. It also doesn't work with the released version. So I add a new issue for that.

server startup:
```
valheim_1  | ###########################################################################
valheim_1  | Valheim Server - Tue Feb  9 12:07:54 CET 2021
valheim_1  |
valheim_1  | Initializing your container...
valheim_1  | ###########################################################################
valheim_1  |
valheim_1  | [Valheim][root]: Switching UID and GID
valheim_1  | [Valheim][root]: Setting up file systems
valheim_1  | [Valheim][root]: Launching as steam...
valheim_1  |
valheim_1  | ###########################################################################
valheim_1  | Valheim Server - Tue Feb  9 03:07:55 PST 2021
valheim_1  | STEAM_UID 1000 - STEAM_GUID 1000
valheim_1  |
valheim_1  | Installing Valheim via Odin
valheim_1  |
valheim_1  | ###########################################################################
```
...
```
valheim_1  | [ODIN][INFO]  - Successfully installed Valheim!
valheim_1  | [Valheim][steam]: Herding Cats...
valheim_1  | [Valheim][steam]: Starting server...
valheim_1  | [ODIN][INFO]  - Setting up start scripts...
valheim_1  | [ODIN][INFO]  - Looking for burial mounds...
valheim_1  | [ODIN][INFO]  - Successfully written /home/steam/valheim/start_server_rusty.sh
valheim_1  | [ODIN][INFO]  - Created the /home/steam/valheim/start_server_rusty.sh script successfully!
valheim_1  | [ODIN][INFO]  - Successfully set /home/steam/valheim/start_server_rusty.sh to executable
valheim_1  | [ODIN][INFO]  - Successfully set /home/steam/valheim/start_server_rusty.sh to executable!
valheim_1  | [ODIN][INFO]  - Exit with code exit code: 0
valheim_1  | [ODIN][INFO]  - Server has started...
valheim_1  | [ODIN][INFO]  - Check out ./output.log for the logs.
valheim_1  | [ODIN][INFO]  - Keep an eye out for "Game server connected" and you server should be live!
valheim_1  |
valheim_1  |
valheim_1  | Valheim Server Started...
valheim_1  |
valheim_1  | Keep an eye out for 'Game server connected' in the log!
valheim_1  | (this indicates its online without any errors.)
valheim_1  |
valheim_1  |
valheim_1  | ###########################################################################
```
...
```
valheim_1  | 02/09/2021 03:08:20: Game server connected
```

**Comment by mbround18** [comment]
@Fabiryn that should be an easy fix :) ill make the change at lunch and toss it up

**Comment by mbround18** [comment]
Alright, my latest push has the timezone fixes. From my testing, it sets the timezone correctly and when I exec into the system it now has the correct timezone. (Tested with PST, CST, and EST)

**Pull request merged**
