### PR TITLE
Shell escape startup script

### PR DESCRIPTION
**Pull request by LovecraftianHorror**
# Description

## Contributions
- I shell escaped certain values getting placed in `rusty_startup_script.sh`

Note: I tested these changes locally with a server named `Odin \o/` and password of `!@#$%^&*()'` and everything worked as intended.

This is done to address the root cause #73 where values in `rusty_startup_script.sh` were not properly being escaped for bash causing unexpected behavior when dealing with ` `, `$`, `\`, etc.

These changes shell escape the name, world, and password which are all the values that you could _expect_ to see containing these special characters. A nice side effect of this change is that it removes the dependency on `tinytemplate` and `serde` since `tinytemplate` was being an absolute pain when it came to certain special characters and was easily replaced with a simple `format!`. This reduced the number of crates compiled even further down to 54 :tada:

Another side note, there is still unexpected behavior when the name, world, or password starts or ends with any amount of `"` due to trimming them with `parse_variable`. I honestly don't know why this is done to begin with, but this will cause a password like `"don't quote me" -me` to become `don't quote me" -me` (note the missing starting `"`) and will likely be a great source of confusion for anyone who encounters it. Is there a reason for doing this? I feel like a user passing in something with a residual starting or ending `"` would be user error and should not be modified. If trimming double-quotes can be removed then I can make that change in this PR too (or feel free to make the change yourself, I'm calling it for the night after submitting this).

## Checklist

- [x] I added one or multiple labels which best describes this PR.
- [ ] I have tested the changes locally.
- [ ] This PR has a reviewer on it. 
- [ ] I have validated my changes in a docker container and on Ubuntu. (Only needed for Odin or Docker Changes)

### CODE REVIEW

**Comment by mbround18** [comment]
Hey @LovecraftianHorror, excellent contribution! Ill take a look at it shortly as I am burning the midnight oil to crank out a separation of concern I would like to make in the rust code. Have a good night! I believe the parse_variable can be stripped out I just need to set up some tests on the various ways docker lets you pass in variable..

```yml
environment: 
  NAME: "test name"
```
vs.
```yml
environment: 
  - NAME="test name"
```

**Comment by LovecraftianHorror** [comment]
Ah that would explain how double quotes might sneak in!

And best of luck on the late night work. Feel free to let me know if there's any rust work you want to get done. I have a list of things I'm planning on working through in Odin, but I'm sure I'll run out of changes eventually 😅

**Comment by mbround18** [comment]
I think it would be best for variables if we standardize on what is acceptable for entry. Even if we solve the issue with quotes in Rust we will still run into issues with quotes in bash. I wish there was a better way to store variables. I was thinking of a potential solution where an `init` function for odin could sanitize the variables and store them in a config file.  Thoughts?

**Comment by LovecraftianHorror** [comment]
So ideally for me everything would be escaped properly so that we're not artificially limiting what is acceptable for different fields.

I also don't think that escaping for things outside of what odin deals with should be handled by odin, just because I don't want the design to be tightly coupled to any of the docker container specifics.

Would it be possible to use some helper bash script or function to allow for easily escaping a given bash string. I threw together the following bash script as a demo. It just escapes the first arg passed in using the same technique I did inside odin

```bash
#!/usr/bin/env bash

INNER_ESC=$(echo $1 | sed "s/'/'\"'\"'/g")
echo "'$INNER_ESC'"
```

**Comment by mbround18** [comment]
> So ideally for me everything would be escaped properly so that we're not artificially limiting what is acceptable for different fields.

Maybe we are over engineering this? :P reading around, it seems valheim server passwords do not support special characters

https://client.citadelservers.com/knowledgebase/363/Changing-password-on-your-Valheim-Game-Server.html

https://www.slythergames.com/2021/02/11/valheim-what-is-a-community-server/

**Comment by LovecraftianHorror** [comment]
Are you sure that's not from people handling it correctly in different tooling? I made a server with the password `!@#$%^&*()'` and was able to connect to the server and play without any issues.

**Comment by LovecraftianHorror** [comment]
I just tested another server with the password `;:'",<.>/?[{]}` and didn't run into any issues connecting there. I'm assume the articles you linked above just don't handle things correctly and push that restriction off onto the user, which I don't agree with.

**Comment by mbround18** [comment]
Okidoki, if you have the time would you mind removing the parse_variable funciton on this branch? Ill take a look at implementing the shell escape

**Comment by LovecraftianHorror** [comment]
`parse_variable` has been removed, and I was able to use `"Don't quote me" -me` as a password :partying_face: 

It's worth noting that if someone accidentally has quotes surrounding some values for their current server then this change will cause issues. Just as a heads up in case any GitHub issues pops up regarding it.

**Comment by mbround18** [comment]
I am working on the escape quotes for now which should help resolve that. If I am successful, I will land my update first to support  quoted variables.

**Comment by mbround18** [comment]
image

**Comment by mbround18** [comment]
Ya know? I might have just created some magic and I love it. Ill toss up a PR in a moment for you to look at but it involves using rust directly and avoiding the whole needing to escape variables.

**Comment by LovecraftianHorror** [comment]
I can take a look later tonight. Im interested in how the server is launched that way.

**Comment by mbround18** [comment]
> I can take a look later tonight. Im interested in how the server is launched that way.

Magiccc :D https://github.com/mbround18/valheim-docker/pull/89 it works very well locally

**Comment by LovecraftianHorror** [comment]
Thats what i was hoping you were moving towards! A daemon seems like a very clean way of handling this :D

I've got a killer migraine at the moment, but will look at it after it goes away.

**Comment by mbround18** [comment]
> I've got a killer migraine at the moment, but will look at it after it goes away.

I hope you feel better! Yeah no rush, feel free to scope it out when you are feeling better! I added an init command which does most of the heavy lifting for variable expansions using json and cleaned up the start command.

**Comment by mbround18** [comment]
Hey @LovecraftianHorror mind if I close this PR?

**Comment by LovecraftianHorror** [comment]
#89 handles the problem in an even better way. Go for it :D

**Pull request closed without merging**
