### PR TITLE
Build and cache based on #153

### LINKED ISSUE #153: [Enhancement] Improve docker image build times
# Cache odin compilation with `cargo chef`

I'm sure you'be noticed, but currently there is a full clean compile each time the `odin` image is built. `cargo chef` helps fix this issue by doing some magic behind the scenes to enable docker to cache the dependencies and all that. I've personally been using it already locally to help with build times when testing. This is the custom dockerfile I've been using for odin:

```dockerfile
FROM lukemathwalker/cargo-chef as planner
WORKDIR /data/odin
COPY . .
RUN cargo chef prepare --recipe-path recipe.json

FROM lukemathwalker/cargo-chef as cacher
WORKDIR /data/odin
COPY --from=planner /data/odin/recipe.json recipe.json
RUN cargo chef cook --release --recipe-path recipe.json

FROM rust as builder
WORKDIR /data/odin
COPY . .
# Copy over the cached dependencies
COPY --from=cacher /data/odin/target target
COPY --from=cacher $CARGO_HOME $CARGO_HOME
RUN cargo build --release --bin odin

FROM rust as runtime
WORKDIR /data/odin
COPY --from=builder /data/odin/target/release/odin /usr/local/bin
ENTRYPOINT ["/usr/local/bin/odin"]
CMD ["--version"]
```

This is basically a barely modified version of the example in `cargo chef`'s README.

# Cache the build info with github actions

Now the next step would be to cache the files so that they can actually be used to speed up CI. It looks like [this action](https://github.com/marketplace/actions/docker-layer-caching) can help with that, but I honestly haven't done any docker image building in CI before so there's possibly better.

### PR DESCRIPTION
**Pull request by mbround18**
# Description

## Contributions
- closes #153 

> Excellent research work @LovecraftianHorror ! 👍 

## Checklist

- [x] I added one or multiple labels which best describes this PR.
- [x] I have tested the changes locally.
- [x] This PR has a reviewer on it. 
- [x] I have validated my changes in a docker container and on Ubuntu. (Only needed for Odin or Docker Changes)

### CODE REVIEW

**Comment by LovecraftianHorror** [comment]
Hmmm, it looks like a lot of time is spent caching all the layers. I wonder if it doesn't scale well with so many layers, would consolidating more of the `ENV` variables in `Dockerfile` help with this? E.g.

```dockerfile
ENV PUID=1000 \
  PGID=1000 \
  TZ=America/Los_Angeles \
  PORT "2456" \
  NAME "Valheim Docker" \
  WORLD "Dedicated" \
  PUBLIC "1" \
  PASSWORD "12345" \
  AUTO_UPDATE "0" \
  AUTO_UPDATE_SCHEDULE "0 1 * * *" \
  ...
```

**Comment by LovecraftianHorror** [comment]
Testing more locally, it looks like `ENV` variables MUST be in name=value format when using multiple like this

**Comment by mbround18** [comment]
> Testing more locally, it looks like `ENV` variables MUST be in name=value format when using multiple like this

Pushed up a change with env vars combined

**Comment by mbround18** [comment]
Looks like no impact for its cache time  :/

**Comment by LovecraftianHorror** [comment]
I wonder what the slowdown is from. Turning on the timestamps shows that it is big layers that take more time, but the transfer rate looks like it all finishes rather fast so it seems like untaring the compressed tarballs is taking up a lot of the time. It's using zstd, so it should decompress really quickly, so I wonder where the slowdown really is? Are there a lot of small files in the layers and is tar slow with lots of small files or something?

It would also likely be better if it was extracting all the tarballs in parallel, but it looks like it extracts them sequentially. That's an issue with the base github cache action from my understanding though.

I'd have to check the logs to be sure, but I don't know how smart the docker layer caching is, so it might still be pulling in now unused layers.

I'll keep poking around and let you know if I find out anything.

**Comment by LovecraftianHorror** [comment]
Alright so it looks like layers that aren't being used anymore are still getting restored which explains why the CI time keeps ballooning. I think this is because it keeps falling back to the restore key since there's no hash for it, so it's possible that essentially removing the restore key will fix this, but at the moment each change is causing more layers to be restored when they aren't needed. In the meantime testing a restore key that doesn't end up restoring all of these old values can be done with

```yaml
- uses: satackey/action-docker-layer-caching@v0.0.11
        # Ignore the failure of a step and avoid terminating the job.
        continue-on-error: true
        with:
            key: docker-layer-caching-${{ github.workflow }}-{hash}
            restore-keys: |
                  docker-layer-caching-${{ github.workflow }}-{hash}
```

Where it uses the same key for the regular hit and the fallback (maybe you can also specify an empty set of restore keys to do the same, I'm not really sure). It's possible that this will fix the issue of ballooning cache times, but if this doesn't do the trick then I'm not really sure what else to try.

I really wish github had some easy way to test actions locally too instead of having to push to the repo.

**Comment by mbround18** [comment]
I am going to say this is good for now, it seems the cache time is still ~2 minutes but based on the last couple builds it stopped increasing with each build.

**Comment by mbround18** [comment]
Hmm that change actually stopped allowing it to cache the stages.

**Comment by LovecraftianHorror** [comment]
So it looks like we're not the only people hitting this issue (satackey/action-docker-layer-caching#55). The people in the thread mention a couple options for automatically changing the cache key to help, which could improve the situation here a bit. It might be worth trying the weekly rotating key.

It looks like it's a relatively recent issue, so hopefully some more work is done to improve the situation.

**Comment by mbround18** [comment]
It seems to be partially fixed for this PR, I wonder if releasing this in main if it would cause the cache to balloon. For now, I am going to merge it in and keep an eye on it. If it starts having issues I will try and rotating the key.

**Comment by LovecraftianHorror** [comment]
I'll leave that up to you :sweat_smile:

It also looks like the cache action being slow to decompress is a known issue too (actions/cache#435). Sadly the wins on time from building the images are mostly taken up by restoring and saving the cache :/

**Pull request merged**
