### PR TITLE
Fix starting up without config

### PR DESCRIPTION
**Pull request by LovecraftianHorror**
# Description

## Contributions

So apparently I should avoid messing with the shell scripts :sweat_smile:

#202 accidentally allowed for running `odin start` before `odin configure` which means that a fully fresh server install or updating from a pre-config.json era would result in a panic from missing `config.json` (I honestly forgot `odin configure` was a thing). This change just extracts out the only bit of `auto_update.sh` that I really cared about and uses that within the startup script instead of calling the whole startup script.

Would it be possible to avoid `odin configure` entirely? From what I can tell `config.json` is only used within `odin` for `start`, so can we just read the env vars within start instead?

## Checklist

- [x] I added one or multiple labels which best describes this PR.
- [x] I have tested the changes locally.
- [ ] This PR has a reviewer on it. 
- [x] I have validated my changes in a docker container and on Ubuntu. (Only needed for Odin or Docker Changes)

### CODE REVIEW

**Comment by LovecraftianHorror** [comment]
Pinging @mbround18 for when you get a time to review since this will hit any new people trying out the current image

**Review by mbround18 — APPROVED** [review]

**Comment by mbround18** [comment]
This does not seem to con odin configure ?

**Comment by mbround18** [comment]
We moved to odin configure because we didn't want to deal with environment variable parsing. Tossing it into a json file allowed them to be sanitized without us having to sanitize them.

**Comment by LovecraftianHorror** [comment]
So the issue was that auto_update getting called from withing start_valheim will end up calling `odin start` from within auto_update before an `odin configure` gets called (since that happens after auto_update within start_valheim)

If you delete config.json and do `docker start` with `UPDATE_ON_STSRTUP` active you'll see `odin` panic

And can't we ignore env var escaping since it doesn't have to be done when daemonizing within odin. The only time it would be needed if if we were doing things like setting up and env for cron or other generating bash scripts

**Comment by mbround18** [comment]
That was the other issue we are avoiding and should consider. `odin configure` avoids having to pass in any server configuration arguments to each of the cron jobs where we would have to escape character. 


Instead of running the auto_update.sh my suggestion would be we just run odin install and if the save directory exists, run the odin backup command before we run odin install.

**Comment by LovecraftianHorror** [comment]
Ah, that makes sense.

And that seems fine too, I was just trying to respect the `AUTO_BACKUP_ON_UPDATE` flag. Feel free to make any changes and merge once you're happy with it. I'm about to go to sleep

**Comment by mbround18** [comment]
I am on the side of a mountain hiking atm in a spot with limited service XP I'll have to make changes once I get home. 

In the mean time sleep well! As a temp work around I suggest beans run odin configure inside the container and restart

**Pull request merged**
