### PR TITLE
[Odin] Fix installation of mods having a UTF-8 BOM in their manifest.json

### PR DESCRIPTION
**Pull request by JulianVallee**
# Description
Remove possible [UTF-8 BOMs](https://en.wikipedia.org/wiki/Byte_order_mark) from mod manifest.json files before deserialization. Serde [does not support](https://github.com/serde-rs/serde/issues/1753) UTF-8 BOMs, actually it suggests handling them manually. Trying to install a mod that has a manifest.json file with a UTF-8 BOM fails with the following error during Odin startup:

```
[ODIN][INFO]  - Installing  https://valheim.thunderstore.io/package/download/OdinPlus/PlantIt/0.1.1,
thread 'main' panicked at 'Failed deserializing manifest: Error("expected value", line: 1, column: 1)', src/odin/mods/mod.rs:103:42,
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace,
```

Using a hex editor the UTF-8 BOM can easily be spotted:
image

## Contributions

- I changed how the manifest.json file is loaded.
- I added removal of UTF-8 BOM from downloaded mod manifest.json files.

## Checklist

- [ ] I added one or multiple labels which best describes this PR.
- [x] I have tested the changes locally.
- [ ] This PR has a reviewer on it.
- [ ] I have validated my changes in a docker container and on Ubuntu. (Only needed for Odin or Docker Changes)

### CODE REVIEW

**Comment by mbround18** [comment]
Queued for pipeline, its getting late for me now, at first glance it looks great! :) excellent job! Tomorrow i will pull it down and run it through the usual ropes.

**Comment by JulianVallee** [comment]
Thanks for the quick feedback! The build task failed due to a formatting/linting issue, should be resolved now.

**Comment by JulianVallee** [comment]
@mbround18 I'm not 100% how to interpret, but looks like linter expects a trailing comma at the ZipArchive use statement?

**Comment by mbround18** [comment]
> 
> 
> @mbround18 I'm not 100% how to interpret, but looks like linter expects a trailing comma at the ZipArchive use statement?

ill pull it down and give it a gander :)

**Review by mbround18 — APPROVED** [review]

**Comment by JulianVallee** [comment]
Thanks a bunch!

**Pull request merged**
